name: SAuth CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 by running Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Logging into GitHub Container Registry on the server..."
            # Login to GHCR on the EC2 instance to pull the image
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pulling the latest image from the registry..."
            # Pull the specific image that was just built for this commit
            docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}

            echo "Stopping and removing the old container..."
            # Stop the old container if it's running, ignore error if it doesn't exist
            docker stop my-app || true
            # Remove the old container
            docker rm my-app || true

            echo "Starting the new container..."
            # Run the new container from the image we just pulled
            docker run -d -p 3000:3000 --name my-app --restart always ghcr.io/${{ github.repository }}:${{ github.sha }}
