name: SAuth

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install

  codeql-analysis:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build-and-scan-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo '{
            "include": [
              {
                "host": "${{ secrets.EC2_HOST }}",
                "name": "production-1"
              },
              {
                "host": "${{ secrets.EC2_HOST2 }}",
                "name": "production-2"
              }
            ]
          }' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  
  deploy:
    needs: [codeql-analysis, build-and-scan-docker-image, prepare-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Deploy to ${{ matrix.name }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            IMAGE_TO_DEPLOY="${{ needs.build-and-scan-docker-image.outputs.image_tag }}"
            sudo usermod -aG docker ${{ secrets.EC2_USERNAME }} || true
            
            echo "Deploying to ${{ matrix.name }} (${{ matrix.host }})"
            echo "Logging into GitHub Container Registry on the server..."
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "Pulling image: ${IMAGE_TO_DEPLOY}"
            docker pull ${IMAGE_TO_DEPLOY}
            
            echo "Stopping and removing the old container..."
            docker stop my-app || true
            docker rm my-app || true
            
            echo "Starting the new container..."
            docker run -d -p 3000:3000 --name my-app --restart always ${IMAGE_TO_DEPLOY}
            
            echo "Deployment complete on ${{ matrix.name }}. App accessible at http://${{ matrix.host }}:3000"

  auto-rollback:
    needs: [deploy]
    if: failure()
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Automatic Rollback on ${{ matrix.name }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Deployment failed on ${{ matrix.name }} - initiating automatic rollback..."
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            PREVIOUS_IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" ${{ github.repository }} | grep -v "latest" | head -n 2 | tail -n 1)
            
            if [ -n "$PREVIOUS_IMAGE" ]; then
              echo "Rolling back ${{ matrix.name }} to: $PREVIOUS_IMAGE"
              docker stop my-app || true
              docker rm my-app || true
              docker run -d -p 3000:3000 --name my-app --restart always $PREVIOUS_IMAGE
              echo "Automatic rollback complete on ${{ matrix.name }}"
            else
              echo "No previous image found for rollback on ${{ matrix.name }}"
              exit 1
            fi