name: SAuth CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # - name: Lint Code with ESLint
      #   run: npm run lint

  codeql-analysis:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build-and-scan-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push image to registry (if scan passes)
        run: docker push ${{ steps.meta.outputs.tags }}

  deploy:
    needs: [codeql-analysis, build-and-scan-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 by running Docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Starting deployment on EC2 instance..."
            sudo usermod -aG docker ${{ secrets.EC2_USERNAME }} || true

            echo "Logging into GitHub Container Registry on the server..."
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pulling the latest image from the registry..."
            docker pull ${{ needs.build-and-scan-docker-image.outputs.image_tag }}

            echo "Stopping and removing the old container..."
            docker stop my-app || true
            docker rm my-app || true

            echo "Starting the new container..."
            docker run -d -p 3000:3000 --name my-app --restart always ${{ needs.build-and-scan-docker-image.outputs.image_tag }}

            echo "Deployment complete lmao fucking asshole. App accessible at http://${{ secrets.EC2_HOST }}:3000"