name: Build, Test, and Deploy Application

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build, Test, and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      # - name: Run unit tests
      #   run: npm test # Replace with your actual test command

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript 

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build-and-push-docker-image:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy-to-development:
    name: Deploy to Development
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        host: ${{ fromJson(secrets.DEV_SERVER_HOSTS) }}
    steps:
      - name: Deploy to Server ${{ matrix.host }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.JUMP_SERVER_HOST }} 
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # 2. From the jump server, securely SSH to the private application server
            echo "--- Starting deployment to private server ${{ matrix.host }} ---"
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.EC2_SSH_PRIVATE_KEY }}"

            ssh -o StrictHostKeyChecking=no -A ${{ secrets.EC2_USERNAME }}@${{ matrix.host }} << 'ENDSSH'
              # 3. These commands run on the FINAL private server
              set -e
              echo "Logging into GHCR on private server..."
              echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

              echo "Pulling latest Docker image..."
              docker pull ghcr.io/${{ github.repository }}:latest

              echo "Stopping and removing old container..."
              docker stop dev-app || true
              docker rm dev-app || true

              echo "Starting new container..."
              docker run -d -p 80:80 --name dev-app --restart always ghcr.io/${{ github.repository }}:latest

              echo "Deployment to ${{ matrix.host }} was successful!"
            ENDSSH

  wait-for-prod-approval:
    name: Wait for Production Approval
    needs: deploy-to-development
    runs-on: ubuntu-latest
    environment: production 
    steps:
      - name: Waiting for approval to deploy to production...
        run: echo "Approval received from reviewers. Proceeding to production."

  deploy-to-production:
    name: Deploy to Production
    needs: wait-for-prod-approval
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        host: ${{ fromJson(secrets.PROD_SERVER_HOSTS) }}
    steps:
      - name: Deploy to Server ${{ matrix.host }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.JUMP_SERVER_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "--- Starting deployment to private server ${{ matrix.host }} ---"
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.EC2_SSH_PRIVATE_KEY }}"

            ssh -o StrictHostKeyChecking=no -A ${{ secrets.EC2_USERNAME }}@${{ matrix.host }} << 'ENDSSH'
              set -e
              echo "Logging into GHCR on private server..."
              echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

              echo "Pulling latest Docker image..."
              docker pull ghcr.io/${{ github.repository }}:latest

              echo "Stopping and removing old container..."
              docker stop prod-app || true
              docker rm prod-app || true

              echo "Starting new container..."
              docker run -d -p 80:80 --name prod-app --restart always ghcr.io/${{ github.repository }}:latest

              echo "Deployment to ${{ matrix.host }} was successful!"
            ENDSSH
