name: SAuth CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      # - name: Lint Code with ESLint
      #   run: npm run lint

  codeql-analysis:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      security-events: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build-and-scan-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [codeql-analysis, build-and-scan-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            sudo usermod -aG docker ${{ secrets.EC2_USERNAME }} || true
            
            echo "Logging into GitHub Container Registry on the server..."
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            echo "Pulling the latest image from the registry..."
            docker pull ghcr.io/decodx09/sauth:latest
            
            echo "Stopping and removing the old container..."
            docker stop my-app || true
            docker rm my-app || true
            
            echo "Starting the new container..."
            docker run -d -p 3000:3000 --name my-app --restart always ghcr.io/decodx09/sauth:latest
            
            echo "Deployment complete. App accessible at http://${{ secrets.EC2_HOST }}:3000"

  auto-rollback:
    needs: [deploy]
    if: failure() && needs.deploy.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Rollback on Deployment Failure
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            echo "Deployment failed - initiating automatic rollback..."
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Get the previous working image (you may need to track this differently)
            PREVIOUS_IMAGE=$(docker images ghcr.io/decodx09/sauth --format "table {{.Repository}}:{{.Tag}}" | grep -v latest | head -n 1 | tr -d ' ')
            
            if [ -n "$PREVIOUS_IMAGE" ]; then
              echo "Rolling back to: $PREVIOUS_IMAGE"
              docker stop my-app || true
              docker rm my-app || true
              docker run -d -p 3000:3000 --name my-app --restart always $PREVIOUS_IMAGE
              echo "Automatic rollback complete to $PREVIOUS_IMAGE"
            else
              echo "No previous image found for rollback"
            fi
