name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Previous image tag to rollback to (e.g., ghcr.io/your-repo:sha12345)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Deployment on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Logging into GitHub Container Registry..."
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pulling the specified image..."
            docker pull ${{ inputs.image_tag }}

            echo "Stopping and removing the current container..."
            docker stop my-app || true
            docker rm my-app || true

            echo "Starting the container with the rollback image..."
            docker run -d -p 3000:3000 --name my-app --restart always ${{ inputs.image_tag }}

            echo "Rollback complete. App accessible at http://${{ secrets.EC2_HOST }}:3000"
