name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'RollBack'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Deployment on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            # Construct the full image name using the tag provided by the user
            IMAGE_NAME="ghcr.io/${{ github.repository }}:${{ github.event.inputs.image_tag }}"

            echo "Logging into GitHub Container Registry..."
            sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pulling the specified image: ${IMAGE_NAME}"
            sudo docker pull ${IMAGE_NAME}

            echo "Stopping and removing the current container..."
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            echo "Starting the container with the rollback image..."
            sudo docker run -d -p 3000:3000 --name my-app --restart always ${IMAGE_NAME}

            echo "Rollback to tag ${{ github.event.inputs.image_tag }} complete."